// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportHTML() {
  return window['go']['main']['App']['ExportHTML']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetStandards() {
  return window['go']['main']['App']['GetStandards']();
}

export function ImportHTML() {
  return window['go']['main']['App']['ImportHTML']();
}

export function ListHistory() {
  return window['go']['main']['App']['ListHistory']();
}

export function LoadAssessment() {
  return window['go']['main']['App']['LoadAssessment']();
}

export function RestoreVersion(arg1) {
  return window['go']['main']['App']['RestoreVersion'](arg1);
}

export function SaveAssessment(arg1) {
  return window['go']['main']['App']['SaveAssessment'](arg1);
}
