// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportHTML():Promise<string>;

export function GetDataDir():Promise<string>;

export function GetStandards():Promise<main.Standards>;

export function ImportHTML():Promise<main.Assessment>;

export function ListHistory():Promise<Array<main.HistoryEntry>>;

export function LoadAssessment():Promise<main.Assessment>;

export function RestoreVersion(arg1:string):Promise<void>;

export function SaveAssessment(arg1:main.Assessment):Promise<void>;
